port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
enable: true
listen: 0.0.0.0:53
enhanced-mode: fake-ip
fake-ip-range: 198.18.0.1/16
nameserver:
- https://1.1.1.1/dns-query
- https://dns.google/dns-query
fallback:
- https://1.0.0.1/dns-query
- https://dns.google/dns-query

proxies:

name: MyVPS
type: ss
server: 107.173.127.112
port: 443
cipher: chacha20-ietf-poly1305
password: "LLTS#ZL#1994#"
udp: true

proxy-groups:

name: Auto
type: select
proxies:

MyVPS

DIRECT

name: Proxy
type: url-test
proxies:

MyVPS
url: http://www.gstatic.com/generate_204
interval: 300

rules:

DOMAIN-SUFFIX,google.com,Proxy

DOMAIN-SUFFIX,youtube.com,Proxy

DOMAIN-SUFFIX,facebook.com,Proxy

DOMAIN-SUFFIX,twitter.com,Proxy

IP-CIDR,10.0.0.0/8,DIRECT

IP-CIDR,192.168.0.0/16,DIRECT

GEOIP,CN,DIRECT

MATCH,Auto
